name: CI/CD Testing for Cisco IOS-XE & IOS-XR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  Test-Validate-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Docstring Check on validate_yaml.py
        run: |
          flake8 --select=D100,D101,D102,D103 validate_yaml.py
          
      - name: Validate devices.yaml Indenting/Formatting
        run: python validate_yaml.py

      - name: Run Docstring Check on test_ssh_connectivity.py
        run: |
          flake8 --select=D100,D101,D102,D103 test_ssh_connectivity.py

      - name: Run SSH Connectivity Test
        run: python test_ssh_connectivity.py

      - name: Run Docstring Check on test_ios_version.py
        run: |
          flake8 --select=D100,D101,D102,D103 test_ios_version.py

      - name: Run IOS-XE Version Test
        run: python test_ios_version.py

