name: CI/CD Testing for Cisco IOS-XE

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  test-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Validate YAML Formatting
        run: python validate_yaml.py

      - name: Run SSH Connectivity Test
        run: python test_ssh_connectivity.py

      - name: Run IOS-XE Version Test
        run: python test_ios_version.py

